spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/poc_hexa
    platform: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver

